export const FILES = [
  {
    id: 1,
    name: "home.tsx",
    logo: "https://dl.svgcdn.com/svg/logos/react.svg",
    location: "src/",
    tags: "React TypeScript",
  },
  {
    id: 2,
    name: "about.html",
    logo: "https://raw.githubusercontent.com/vscode-icons/vscode-icons/master/icons/file_type_html.svg",
    location: "src/",
    tags: "HTML",
  },
  {
    id: 3,
    name: "projects.js",
    logo: "https://raw.githubusercontent.com/vscode-icons/vscode-icons/master/icons/file_type_js.svg",
    location: "src/",
    tags: "JavaScript",
  },
  {
    id: 4,
    name: "skills.json",
    logo: "https://raw.githubusercontent.com/vscode-icons/vscode-icons/master/icons/file_type_json.svg",
    location: "src/",
    tags: "JSON",
  },
  {
    id: 5,
    name: "experience.ts",
    logo: "https://raw.githubusercontent.com/vscode-icons/vscode-icons/master/icons/file_type_typescript.svg",
    location: "src/",
    tags: "TypeScript",
  },
  {
    id: 6,
    name: "contact.css",
    logo: "https://raw.githubusercontent.com/vscode-icons/vscode-icons/master/icons/file_type_css.svg",
    location: "src/",
    tags: "CSS",
  },
  {
    id: 7,
    name: "README.md",
    logo: "https://raw.githubusercontent.com/vscode-icons/vscode-icons/master/icons/file_type_markdown.svg",
    location: "./",
    tags: "Markdown",
  },
  {
    id: 8,
    name: "Nitin_Singh_Negi_resume.pdf",
    logo: "https://raw.githubusercontent.com/vscode-icons/vscode-icons/master/icons/file_type_pdf.svg",
    location: "./resume.pdf",
    isFile: true,
  },
];
